image: node:17-alpine3.14

variables:
  NETLIFY_SITE_ID: $NETLIFY_SITE_ID
  NETLIFY_AUTH_TOKEN: $NETLIFY_AUTH_TOKEN

stages:
  - preview

preview:
  stage: preview
  tags:
    - dalfcs_docker_autoscale
  script:
    - npm ci
    - apk add --no-cache zip curl
    - npm run build
    - npm install netlify-cli --save-dev
    - npx netlify deploy --prod --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --dir dist/
  artifacts:
    paths:
      - dist
  cache:
    paths:
      - .npm/
    key:
      files:
        - package-lock.json
      